### ISSUE TITLE
Can we run the container without -t option?

### ISSUE THREAD

**Issue by reevelau** [sequenceiq/docker-e2e-protractor#1]
I am integration this docker image with our CI system which triggered by ant script. Ant exec task doesn't provide tty, so when running the container with `docker -it` the sessions will failed with error message "the input device is not a TTY".

But when I tried to run the docker container with the arguments but "docker -i" or "docker -t" only, the chrome crash

[08:23:48] I/direct - Using ChromeDriver directly...
[08:23:48] I/launcher - Running 1 instances of WebDriver
[08:24:49] E/launcher - unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-53-generic x86_64)
[08:24:49] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-53-generic x86_64)
    at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/direct.js:68:26)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:198:43)
    at /usr/lib/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/lib/node_modules/protractor/node_modules/q/q.js:137:13)

**Comment by aszegedi** [comment]
Hi! So sorry for my late response!

Yes, we can and the "only way" you can run this on CI with no `-i`.

How I use this on CI:
...
```sh
echo "Refresh the Test Runner Docker image"
docker pull hortonworks/docker-e2e-protractor

export TEST_CONTAINER_NAME=hdc-e2e

echo "Checking stopped containers"
if [[ -n "$(docker ps -a -f status=exited -f status=dead -q)" ]]; then
  echo "Delete stopped containers"
  docker rm $(docker ps -a -f status=exited -f status=dead -q)
else
  echo "There is no Exited or Dead container"
fi

echo "Checking " $TEST_CONTAINER_NAME " container is running"
if [[ "$(docker inspect -f {{.State.Running}} $TEST_CONTAINER_NAME 2> /dev/null)" == "true" ]]; then
  echo "Delete the running " $TEST_CONTAINER_NAME " container"
  docker rm -f $TEST_CONTAINER_NAME
fi

CLOUD_URL_RESPONSE=$(curl -k --write-out %{http_code} --silent --output /dev/null $CLOUD_URL/sl)
echo $CLOUD_URL " HTTP status code is: " $CLOUD_URL_RESPONSE
if [[ $CLOUD_URL_RESPONSE -ne 200 ]]; then
    echo $CLOUD_URL " Web GUI is not accessible!"
    RESULT=1
else
    docker run -i \
    --privileged \
    --rm \
    --name $TEST_CONTAINER_NAME \
    --env-file $ENVFILE \
    -v $(pwd):/protractor/project \
    -v /dev/shm:/dev/shm \
    hortonworks/docker-e2e-protractor e2e.conf.js --suite $TEST_SUITE
    RESULT=$?
fi
```
...
