### ISSUE TITLE
Tests are failing with the image version release-1.0

### ISSUE THREAD

**Issue by metawiz** [sequenceiq/docker-e2e-protractor#2]
I tried to run a set of e2e tests (angular seed project) using both image tags available:
- latest, built 5 months ago
- release-1.0, built 2 months ago

Tests are working fine with 'latest' image but not with the one with version 'release-1.0'. The error I get is:

[13:51:53] E/launcher - chrome not reachable
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.10.0-20-generic x86_64)
[13:51:53] E/launcher - WebDriverError: chrome not reachable
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.10.0-20-generic x86_64)
    at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/usr/lib/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/usr/lib/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[13:51:53] E/launcher - Process exited with error code 199

The problem seem to be related to the difference in versions for protractor and chrome.

**Comment by aszegedi** [comment]
Hi! So sorry for my late response!

Yes, you are right. I suppose also, that GChrome was not compatible that Protractor...

How I use this and working on CI:
...
```sh
echo "Refresh the Test Runner Docker image"
docker pull hortonworks/docker-e2e-protractor

export TEST_CONTAINER_NAME=hdc-e2e

echo "Checking stopped containers"
if [[ -n "$(docker ps -a -f status=exited -f status=dead -q)" ]]; then
  echo "Delete stopped containers"
  docker rm $(docker ps -a -f status=exited -f status=dead -q)
else
  echo "There is no Exited or Dead container"
fi

echo "Checking " $TEST_CONTAINER_NAME " container is running"
if [[ "$(docker inspect -f {{.State.Running}} $TEST_CONTAINER_NAME 2> /dev/null)" == "true" ]]; then
  echo "Delete the running " $TEST_CONTAINER_NAME " container"
  docker rm -f $TEST_CONTAINER_NAME
fi

CLOUD_URL_RESPONSE=$(curl -k --write-out %{http_code} --silent --output /dev/null $CLOUD_URL/sl)
echo $CLOUD_URL " HTTP status code is: " $CLOUD_URL_RESPONSE
if [[ $CLOUD_URL_RESPONSE -ne 200 ]]; then
    echo $CLOUD_URL " Web GUI is not accessible!"
    RESULT=1
else
    docker run -i \
    --privileged \
    --rm \
    --name $TEST_CONTAINER_NAME \
    --env-file $ENVFILE \
    -v $(pwd):/protractor/project \
    -v /dev/shm:/dev/shm \
    hortonworks/docker-e2e-protractor:release-1.0 e2e.conf.js --suite $TEST_SUITE
    RESULT=$?
fi
```
...
